---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV['KITCHEN_DOCKER_SOCKET'] || "unix:///var/run/docker.sock" %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
    attributes:
      matt-base:
        python3:
          version: '3.6'

suites:
  - name: default
    run_list:
      - recipe[matt-base::default]
    attributes:

  - name: python
    run_list:
      - recipe[matt-base::default]
      - recipe[matt-base::python]
    attributes:

  - name: ruby
    run_list:
      - recipe[matt-base::default]
      - recipe[matt-base::ruby]
    attributes:

  - name: full
    run_list:
      - recipe[matt-base::default]
      - recipe[matt-base::python]
      - recipe[matt-base::ruby]
      - recipe[matt-base::vim]
    attributes:
