name             'matt-base'
maintainer       'Matt Chun-Lum'
maintainer_email 'mchunlum@gmail.com'
license          'mit'
description      'Installs/Configures matt-base'
long_description 'Installs/Configures matt-base'
version          '1.3.0'

depends 'apt'
depends 'ark'
depends 'build-essential'
depends 'cmake'
depends 'git'
depends 'poise-python'
depends 'ruby_rbenv'
depends 'ssh_known_hosts'
depends 'tig'
depends 'zsh'
