---
platform: linux

image_resource:
  type: docker-image
  source: {repository: mattcl/chefdk-kitchen-docker}

inputs:
  - name: repo

outputs:
  - name: packaged-cookbook

run:
  path: repo/ci/package.sh
