---
resource_types:
  - name: slack-alert
    type: docker-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mattcl/matt-base.git
      branch: master

  - name: notify
    type: slack-alert
    source:
      url: ((slack_hook))

jobs:
  - name: converge
    public: false
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: repo
        trigger: true
      - aggregate:
          - task: converge-18.04
            file: repo/ci/converge.yml
            params:
              KITCHEN_DOCKER_SOCKET: ((docker_socket))
              suite: full-ubuntu-1804
        on_failure:
          put: notify
          params:
            alert_type: failed
        on_abort:
          put: notify
          params:
            alert_type: aborted

  - name: package
    public: false
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: repo
        trigger: true
        passed: [converge]
      - task: berks-package
        file: repo/ci/package.yml
        on_failure:
          put: notify
          params:
            alert_type: failed
        on_abort:
          put: notify
          params:
            alert_type: aborted
        on_success:
          put: notify
          params:
            alert_type: success
