---
resources:
  - name: repo
    type: git
    source:
      url: https://github.com/mattcl/matt-base.git

jobs:
  - name: release
    public: false
    serial: true
    build_logs_to_retain: 100
    plan:
      - get: repo
      - task: converge-1404
        file: repo/ci/converge.yml
        params:
          KITCHEN_DOCKER_SOCKET: {{docker-socket}}
          suite: full-ubuntu-1404
        ensure:
          file: repo/ci/cleanup.sh
          params:
            KITCHEN_DOCKER_SOCKET: {{docker-socket}}
            suite: full-ubuntu-1404

